### ISSUE TITLE
FIR not shown

### ISSUE THREAD

**Issue by dsl94** [BunZe/yaam-client#5]
Yesterday I was flying from Belgrade (LYBE) to Amsterdam and I had LYBA_CTR control online which wasn't shown on the map.
That FIR should cover territory of Serbia.
Also on vatsim there is Adria control which covers territories of Serbia, Bosnia, Croatia, Slovenia, Macedonia, Albania and Montenegro.

Can you add those?

p.s. I love this map it is much better then that old vatspy or other ancient maps

**Comment by BunZe** [comment]
Thanks for the great feedback.
Unfortunately FIR accuracy is not at the top most priority right now. Mostly because I might merge my map with another developers map, who has much more accurate FIR data. Once I'm settled on where development is going, I'll start working on a community-driven FIR database, to give the most accurate I can for the entire map.
